// Russian translations for field labels and descriptions.
// Used by ru.ts instead of the English defaults from constants.ts.

export const RU_FIELD_LABELS: Record<string, string> = {
  model: 'Модель по умолчанию',
  model_context_length: 'Окно контекста',
  fallback_providers: 'Резервные модели',
  toolsets: 'Включённые наборы инструментов',
  timezone: 'Часовой пояс',
  'display.personality': 'Личность',
  'display.show_reasoning': 'Блоки рассуждений',
  'agent.max_turns': 'Макс. шагов агента',
  'agent.image_input_mode': 'Вложения изображений',
  'terminal.cwd': 'Рабочая директория',
  'terminal.backend': 'Бэкенд выполнения',
  'terminal.timeout': 'Тайм-аут команды',
  'terminal.persistent_shell': 'Постоянная оболочка',
  'terminal.env_passthrough': 'Передача переменных окружения',
  file_read_max_chars: 'Лимит чтения файла',
  'tool_output.max_bytes': 'Лимит вывода терминала',
  'tool_output.max_lines': 'Лимит страницы файла',
  'tool_output.max_line_length': 'Лимит длины строки',
  'code_execution.mode': 'Режим выполнения кода',
  'approvals.mode': 'Режим подтверждений',
  'approvals.timeout': 'Тайм-аут подтверждения',
  'approvals.mcp_reload_confirm': 'Подтверждать перезагрузку MCP',
  command_allowlist: 'Белый список команд',
  'security.redact_secrets': 'Скрывать секреты',
  'security.allow_private_urls': 'Разрешить приватные URL',
  'browser.allow_private_urls': 'Приватные URL в браузере',
  'browser.auto_local_for_private_urls': 'Локальный браузер для приватных URL',
  'checkpoints.enabled': 'Контрольные точки файлов',
  'checkpoints.max_snapshots': 'Лимит контрольных точек',
  'voice.record_key': 'Горячая клавиша записи',
  'voice.max_recording_seconds': 'Макс. длительность записи',
  'voice.auto_tts': 'Озвучивать ответы',
  'stt.enabled': 'Распознавание речи',
  'stt.provider': 'Провайдер распознавания речи',
  'stt.local.model': 'Локальная модель транскрипции',
  'stt.local.language': 'Язык транскрипции',
  'stt.elevenlabs.model_id': 'Модель ElevenLabs STT',
  'stt.elevenlabs.language_code': 'Язык ElevenLabs',
  'stt.elevenlabs.tag_audio_events': 'Теги аудиособытий',
  'stt.elevenlabs.diarize': 'Диаризация спикеров',
  'tts.provider': 'Провайдер синтеза речи',
  'tts.edge.voice': 'Голос Edge',
  'tts.openai.model': 'Модель OpenAI TTS',
  'tts.openai.voice': 'Голос OpenAI',
  'tts.elevenlabs.voice_id': 'Голос ElevenLabs',
  'tts.elevenlabs.model_id': 'Модель ElevenLabs',
  'memory.memory_enabled': 'Постоянная память',
  'memory.user_profile_enabled': 'Профиль пользователя',
  'memory.memory_char_limit': 'Бюджет памяти',
  'memory.user_char_limit': 'Бюджет профиля',
  'memory.provider': 'Провайдер памяти',
  'context.engine': 'Движок контекста',
  'compression.enabled': 'Авто-сжатие',
  'compression.threshold': 'Порог сжатия',
  'compression.target_ratio': 'Целевое сжатие',
  'compression.protect_last_n': 'Защищённые последние сообщения',
  'agent.api_max_retries': 'Повторы API',
  'agent.service_tier': 'Уровень сервиса',
  'agent.tool_use_enforcement': 'Принудительное использование инструментов',
  'delegation.model': 'Модель подагента',
  'delegation.provider': 'Провайдер подагента',
  'delegation.max_iterations': 'Лимит ходов подагента',
  'delegation.max_concurrent_children': 'Параллельные подагенты',
  'delegation.child_timeout_seconds': 'Тайм-аут подагента',
  'delegation.reasoning_effort': 'Усилие рассуждений подагента',
  'updates.non_interactive_local_changes': 'Локальные изменения при обновлении'
}

export const RU_FIELD_DESCRIPTIONS: Record<string, string> = {
  model: 'Используется для новых чатов, если не выбрана другая модель.',
  model_context_length: 'Оставьте 0 для автоматического определения окна контекста модели.',
  fallback_providers: 'Резервные провайдеры:модели, если основная модель не работает.',
  'display.personality': 'Стиль ассистента по умолчанию для новых сессий.',
  timezone: 'Используется когда Hermes нужен местный часовой пояс. Пустое значение — системный.',
  'display.show_reasoning': 'Показывать секции рассуждений, если их предоставляет бэкенд.',
  'agent.image_input_mode': 'Управляет отправкой вложений изображений в модель.',
  'terminal.cwd': 'Папка по умолчанию для инструментов и терминала.',
  'code_execution.mode': 'Насколько строго выполнение кода привязано к текущему проекту.',
  'terminal.persistent_shell': 'Сохранять состояние оболочки между командами.',
  'terminal.env_passthrough': 'Переменные окружения для передачи в выполнение инструментов.',
  file_read_max_chars: 'Максимум символов за одно чтение файла.',
  'approvals.mode': 'Как Hermes обрабатывает команды, требующие подтверждения.',
  'approvals.timeout': 'Сколько времени ждать подтверждения до тайм-аута.',
  'security.redact_secrets': 'Скрывать обнаруженные секреты из контекста модели.',
  'checkpoints.enabled': 'Создавать снимки перед редактированием файлов.',
  'memory.memory_enabled': 'Сохранять долгосрочную память для будущих сессий.',
  'memory.user_profile_enabled': 'Поддерживать компактный профиль предпочтений пользователя.',
  'context.engine': 'Стратегия управления длинными разговорами при приближении к лимиту контекста.',
  'compression.enabled': 'Сжимать старый контекст при длинных разговорах.',
  'voice.auto_tts': 'Автоматически озвучивать ответы ассистента.',
  'stt.enabled': 'Включить локальное или облачное распознавание речи.',
  'stt.elevenlabs.language_code': 'Код языка ISO-639-3. Пустое — автоопределение.',
  'agent.max_turns': 'Максимальное количество ходов с вызовом инструментов.',
  'updates.non_interactive_local_changes':
    'При обновлении из приложения: stash — сохранить локальные правки, discard — отбросить.'
}
