import { RU_FIELD_DESCRIPTIONS, RU_FIELD_LABELS } from '@/app/settings/ru-constants'

import type { Translations } from './types'

export const ru: Translations = {
  common: {
    save: 'Сохранить',
    saving: 'Сохранение…',
    cancel: 'Отмена',
    close: 'Закрыть',
    confirm: 'Подтвердить',
    delete: 'Удалить',
    refresh: 'Обновить',
    retry: 'Повторить',
    on: 'Вкл.',
    off: 'Выкл.',
    loadingConfig: 'Загрузка конфигурации Hermes...',
    loadingKeys: 'Загрузка API-ключей и учётных данных...',
    loadingModel: 'Загрузка конфигурации модели...',
    loadingGateway: 'Загрузка настроек шлюза...',
    loadingMcp: 'Загрузка MCP-серверов...',
    loadingProviders: 'Загрузка провайдеров...',
    loadingSessions: 'Загрузка архивных сессий…',
    allProfiles: 'Все профили',
    deletePermanently: 'Удалить безвозвратно'
  },

  boot: {
    ready: 'Hermes Desktop готов',
    desktopBootFailedWithMessage: message => `Ошибка запуска десктопа: ${message}`,
    steps: {
      connectingGateway: 'Подключение к шлюзу',
      loadingSettings: 'Загрузка настроек Hermes',
      loadingSessions: 'Загрузка недавних сессий',
      startingDesktopConnection: 'Запуск десктопного соединения',
      startingHermesDesktop: 'Запуск Hermes Desktop…'
    },
    errors: {
      backgroundExited: 'Фоновый процесс Hermes завершился.',
      backgroundExitedDuringStartup: 'Фоновый процесс Hermes завершился во время запуска.',
      backendStopped: 'Бэкенд остановлен',
      desktopBootFailed: 'Ошибка запуска десктопа',
      gatewaySignInRequired: 'Требуется вход в шлюз',
      ipcBridgeUnavailable: 'IPC-мост десктопа недоступен.'
    },
    failure: {
      title: 'Hermes не удалось запустить',
      description:
        'Фоновый шлюз не запустился. Попробуйте один из вариантов восстановления ниже. Ваши чаты и настройки не удаляются.',
      remoteTitle: 'Требуется вход в удалённый шлюз',
      remoteDescription:
        'Сессия удалённого шлюза истекла. Войдите снова для переподключения. Ваши чаты и настройки не удаляются.',
      retry: 'Повторить',
      repairInstall: 'Восстановить установку',
      useLocalGateway: 'Использовать локальный шлюз',
      openLogs: 'Открыть журналы',
      repairHint: 'Восстановление запускает установщик заново и может занять несколько минут на новом компьютере.',
      remoteSignInHint: 'Открывает окно входа в шлюз. «Локальный шлюз» переключает на встроенный бэкенд.',
      hideRecentLogs: 'Скрыть недавние журналы',
      showRecentLogs: 'Показать недавние журналы',
      signedInTitle: 'Вход выполнен',
      signedInMessage: 'Переподключение к удалённому шлюзу…',
      signInIncompleteTitle: 'Вход не завершён',
      signInIncompleteMessage: 'Окно входа закрылось до завершения аутентификации.',
      signInFailed: 'Ошибка входа',
      signInToRemoteGateway: 'Войти в удалённый шлюз',
      signInWithProvider: provider => `Войти через ${provider}`,
      identityProvider: 'ваш провайдер аутентификации'
    }
  },

  notifications: {
    region: 'Уведомления',
    hide: 'Скрыть',
    show: 'Показать',
    more: count => `Ещё ${count} ${count === 1 ? 'уведомление' : 'уведомлений'}`,
    clearAll: 'Очистить все',
    dismiss: 'Отклонить уведомление',
    details: 'Подробности',
    copyDetail: 'Копировать подробность',
    copyDetailFailed: 'Не удалось скопировать подробность уведомления',
    backendOutOfDateTitle: 'Бэкенд устарел',
    backendOutOfDateMessage:
      'Ваш бэкенд Hermes старше этой версии десктопа и может работать некорректно. Обновите для совместимости.',
    updateHermes: 'Обновить Hermes',
    updateReadyTitle: 'Обновление готово',
    updateReadyMessage: count => `Доступно ${count} нов${count === 1 ? 'ое изменение' : 'ых изменений'}.`,
    seeWhatsNew: 'Что нового',
    errors: {
      elevenLabsNeedsKey: 'Для STT ElevenLabs нужен ELEVENLABS_API_KEY.',
      elevenLabsRejectedKey: 'ElevenLabs отклонил API-ключ (401).',
      methodNotAllowed:
        'Бэкенд десктопа отклонил запрос (405 Method Not Allowed). Попробуйте перезапустить Hermes Desktop.',
      microphonePermission: 'Доступ к микрофону запрещён.',
      openaiRejectedApiKey: 'OpenAI отклонил API-ключ.',
      openaiRejectedApiKeyWithStatus: status => `OpenAI отклонил API-ключ (${status} invalid_api_key).`,
      openaiTtsNeedsKey: 'Для TTS OpenAI нужен VOICE_TOOLS_OPENAI_KEY или OPENAI_API_KEY.'
    }
  },

  titlebar: {
    hideSidebar: 'Скрыть боковую панель',
    showSidebar: 'Показать боковую панель',
    search: 'Поиск',
    searchTitle: 'Поиск сессий, видов и действий',
    swapSidebarSides: 'Поменять стороны панелей',
    swapSidebarSidesTitle: 'Поменять местами панели сессий и файлового браузера',
    hideRightSidebar: 'Скрыть правую панель',
    showRightSidebar: 'Показать правую панель',
    muteHaptics: 'Отключить тактильную отдачу',
    unmuteHaptics: 'Включить тактильную отдачу',
    openSettings: 'Открыть настройки'
  },

  language: {
    label: 'Язык',
    description: 'Выберите язык десктопного интерфейса.',
    saving: 'Сохранение языка…',
    saveError: 'Не удалось изменить язык'
  },

  settings: {
    closeSettings: 'Закрыть настройки',
    exportConfig: 'Экспорт конфигурации',
    importConfig: 'Импорт конфигурации',
    resetToDefaults: 'Сбросить к настройкам по умолчанию',
    resetConfirm: 'Сбросить все настройки Hermes к значениям по умолчанию?',
    exportFailed: 'Ошибка экспорта',
    resetFailed: 'Ошибка сброса',
    nav: {
      gateway: 'Шлюз',
      apiKeys: 'Инструменты и ключи',
      mcp: 'MCP',
      archivedChats: 'Архивные чаты',
      about: 'О приложении',
      providers: 'Провайдеры',
      accounts: 'Аккаунты',
      apiKeysSub: 'API-ключи',
      tools: 'Инструменты',
      settingsSub: 'Настройки'
    },
    sections: {
      model: 'Модель',
      chat: 'Чат',
      appearance: 'Внешний вид',
      workspace: 'Рабочая область',
      safety: 'Безопасность',
      memory: 'Память и контекст',
      voice: 'Голос',
      advanced: 'Дополнительно'
    },
    searchPlaceholder: {
      about: 'О Hermes Desktop',
      config: 'Поиск настроек...',
      gateway: 'Подключение к шлюзу...',
      keys: 'Поиск API-ключей...',
      mcp: 'Поиск MCP-серверов...',
      sessions: 'Поиск архивных сессий...'
    },
    modeOptions: {
      light: { label: 'Светлая', description: 'Светлые поверхности десктопа' },
      dark: { label: 'Тёмная', description: 'Рабочее пространство без бликов' },
      system: { label: 'Системная', description: 'Следовать оформлению ОС' }
    },
    appearance: {
      title: 'Внешний вид',
      intro:
        'Настройки отображения, специфичные для десктопа. Режим управляет яркостью; тема — палитрой акцентов и стилем чат-пузырей.',
      colorMode: 'Цветовой режим',
      colorModeDesc: 'Выберите фиксированный режим или позвольте Hermes следовать системной настройке.',
      toolViewTitle: 'Отображение вызовов инструментов',
      toolViewDesc: '«Продукт» скрывает сырые данные инструментов; «Технический» показывает полный ввод/вывод.',
      product: 'Продукт',
      productDesc: 'Понятная активность инструментов с краткими описаниями.',
      technical: 'Технический',
      technicalDesc: 'Показывать сырые аргументы/результаты и подробные детали.',
      themeTitle: 'Тема',
      themeDesc: 'Палитры только для десктопа. Выбранный режим применяется поверх.'
    },
    fieldLabels: RU_FIELD_LABELS,
    fieldDescriptions: RU_FIELD_DESCRIPTIONS,
    about: {
      heading: 'Hermes Desktop',
      version: value => `Версия ${value}`,
      versionUnavailable: 'Версия недоступна',
      updates: 'Обновления',
      checkNow: 'Проверить сейчас',
      checking: 'Проверка…',
      seeWhatsNew: 'Что нового',
      releaseNotes: 'Примечания к выпуску',
      onLatest: 'У вас последняя версия.',
      installing: 'Сейчас устанавливается обновление.',
      cantUpdate: 'Эта сборка не может обновить себя изнутри приложения.',
      cantReach: 'Не удалось связаться с сервером обновлений.',
      tapCheck: 'Нажмите «Проверить сейчас» для поиска обновлений.',
      updateReady: count => `Новое обновление готово (${count} изменени${count === 1 ? 'е' : 'й'}).`,
      lastChecked: age => `Последняя проверка: ${age}`,
      justNowSuffix: ' · только что',
      automaticUpdates: 'Автоматические обновления',
      automaticUpdatesDesc:
        'Hermes автоматически проверяет обновления в фоне и уведомляет вас, когда они доступны.',
      branchCommit: (branch, commit) => `Ветка ${branch} · Коммит ${commit}`,
      never: 'никогда',
      justNow: 'только что',
      minAgo: count => `${count} мин. назад`,
      hoursAgo: count => `${count} ч. назад`,
      daysAgo: count => `${count} дн. назад`
    }
  },

  skills: {
    tabSkills: 'Навыки',
    tabToolsets: 'Наборы инструментов',
    all: 'Все',
    searchSkills: 'Поиск навыков...',
    searchToolsets: 'Поиск наборов инструментов...',
    refresh: 'Обновить навыки',
    refreshing: 'Обновление навыков',
    loading: 'Загрузка возможностей...',
    noSkillsTitle: 'Навыки не найдены',
    noSkillsDesc: 'Попробуйте расширить поиск или другую категорию.',
    noToolsetsTitle: 'Наборы инструментов не найдены',
    noToolsetsDesc: 'Попробуйте расширить запрос.',
    noDescription: 'Описание отсутствует.',
    configured: 'Настроено',
    needsKeys: 'Требуются ключи',
    toolsetsEnabled: (enabled, total) => `${enabled}/${total} наборов включено`,
    configureToolset: label => `Настроить ${label}`,
    toggleToolset: label => `Переключить набор ${label}`,
    skillsLoadFailed: 'Не удалось загрузить навыки',
    toolsetsRefreshFailed: 'Не удалось обновить наборы инструментов',
    skillEnabled: 'Навык включён',
    skillDisabled: 'Навык отключён',
    toolsetEnabled: 'Набор инструментов включён',
    toolsetDisabled: 'Набор инструментов отключён',
    appliesToNewSessions: name => `${name} применяется к новым сессиям.`,
    failedToUpdate: name => `Не удалось обновить ${name}`
  },

  agents: {
    close: 'Закрыть агентов',
    title: 'Дерево подчинения',
    subtitle: 'Активность подагентов для текущего хода.',
    emptyTitle: 'Нет активных подагентов',
    emptyDesc: 'Когда ход делегирует работу, дочерние агенты транслируют прогресс сюда.',
    running: 'Выполняется',
    failed: 'Ошибка',
    done: 'Готово',
    streaming: 'Трансляция',
    files: 'Файлы',
    moreFiles: count => `+${count} ещё`,
    delegation: index => `Делегирование ${index}`,
    workers: count => `${count} воркеров`,
    workersActive: count => `${count} активных`,
    agentsCount: count => `${count} ${count === 1 ? 'агент' : 'агентов'}`,
    activeCount: count => `${count} активных`,
    failedCount: count => `${count} с ошибкой`,
    toolsCount: count => `${count} инструментов`,
    filesCount: count => `${count} файлов`,
    updatedAgo: age => `обновлено ${age}`,
    ageNow: 'сейчас',
    ageSeconds: seconds => `${seconds}с назад`,
    ageMinutes: minutes => `${minutes}м назад`,
    ageHours: hours => `${hours}ч назад`,
    durationSeconds: seconds => `${seconds}с`,
    durationMinutes: (minutes, seconds) => `${minutes}м ${seconds}с`,
    tokensK: k => `${k}k токенов`,
    tokens: value => `${value} токенов`
  },

  commandCenter: {
    close: 'Закрыть центр команд',
    searchPlaceholder: 'Поиск сессий, видов и действий',
    sections: { sessions: 'Сессии', system: 'Система', usage: 'Использование' },
    sectionDescriptions: {
      sessions: 'Поиск и управление сессиями',
      system: 'Статус, журналы и системные действия',
      usage: 'Токены, стоимость и активность навыков'
    },
    nav: {
      newChat: { title: 'Новая сессия', detail: 'Начать новую сессию' },
      settings: { title: 'Настройки', detail: 'Настроить Hermes Desktop' },
      skills: { title: 'Навыки и инструменты', detail: 'Включить навыки, наборы и провайдеры' },
      messaging: { title: 'Мессенджеры', detail: 'Настроить Telegram, Slack, Discord и др.' },
      artifacts: { title: 'Артефакты', detail: 'Просмотр созданных файлов' }
    },
    sectionEntries: {
      sessions: { title: 'Панель сессий', detail: 'Поиск, закрепление и управление сессиями' },
      system: { title: 'Системная панель', detail: 'Статус шлюза, журналы, перезапуск/обновление' },
      usage: { title: 'Панель использования', detail: 'Токены, стоимость и активность навыков' }
    },
    providerNavigate: 'Перейти',
    providerSessions: 'Сессии',
    refresh: 'Обновить',
    refreshing: 'Обновление...',
    noResults: 'Совпадений не найдено.',
    pinSession: 'Закрепить сессию',
    unpinSession: 'Открепить сессию',
    exportSession: 'Экспортировать сессию',
    deleteSession: 'Удалить сессию',
    noSessions: 'Сессий пока нет.',
    gatewayRunning: 'Шлюз мессенджеров работает',
    gatewayStopped: 'Шлюз мессенджеров остановлен',
    hermesActiveSessions: (version, count) => `Hermes ${version} · Активных сессий: ${count}`,
    restartMessaging: 'Перезапустить мессенджеры',
    updateHermes: 'Обновить Hermes',
    actionRunning: 'выполняется',
    actionDone: 'готово',
    actionFailed: 'ошибка',
    actionStartedWaiting: 'Действие начато, ожидание статуса...',
    loadingStatus: 'Загрузка статуса...',
    recentLogs: 'Недавние журналы',
    noLogs: 'Журналы ещё не загружены.',
    days: count => `${count}д`,
    statSessions: 'Сессии',
    statApiCalls: 'Вызовы API',
    statTokens: 'Токены вх/вых',
    statCost: 'Оценка стоимости',
    actualCost: cost => `фактически ${cost}`,
    loadingUsage: 'Загрузка данных использования...',
    noUsage: period => `Нет данных за последние ${period} дн.`,
    retry: 'Повторить',
    dailyTokens: 'Токены по дням',
    input: 'вход',
    output: 'выход',
    noDailyActivity: 'Нет дневной активности.',
    topModels: 'Популярные модели',
    noModelUsage: 'Данных по моделям пока нет.',
    topSkills: 'Популярные навыки',
    noSkillActivity: 'Данных по навыкам пока нет.',
    actions: count => `${count} действий`
  },

  messaging: {
    search: 'Поиск мессенджеров...',
    loading: 'Загрузка платформ мессенджеров...',
    loadFailed: 'Не удалось загрузить платформы мессенджеров',
    states: {
      connected: 'Подключено',
      connecting: 'Подключение',
      disabled: 'Отключено',
      fatal: 'Ошибка',
      gateway_stopped: 'Шлюз мессенджеров остановлен',
      not_configured: 'Требуется настройка',
      pending_restart: 'Требуется перезапуск',
      retrying: 'Повторная попытка',
      startup_failed: 'Ошибка запуска'
    },
    unknown: 'Неизвестно',
    hintPendingRestart: 'Перезапустите шлюз из строки состояния для применения изменений.',
    hintGatewayStopped: 'Запустите шлюз из строки состояния для подключения.',
    credentialsSet: 'Учётные данные заданы',
    needsSetup: 'Требуется настройка',
    gatewayStopped: 'Шлюз мессенджеров остановлен',
    getCredentials: 'Получить учётные данные',
    openSetupGuide: 'Открыть руководство по настройке',
    required: 'Обязательно',
    recommended: 'Рекомендуется',
    advanced: count => `Дополнительно (${count})`,
    noTokenNeeded: 'Для этой платформы здесь не нужен токен. Используйте руководство выше, затем включите ниже.',
    enabled: 'Включено',
    disabled: 'Отключено',
    unsavedChanges: 'Несохранённые изменения',
    saving: 'Сохранение...',
    saveChanges: 'Сохранить изменения',
    saved: 'Сохранено',
    replaceValue: 'Заменить текущее значение',
    openDocs: 'Открыть документацию',
    clearField: key => `Очистить ${key}`,
    enableAria: name => `Включить ${name}`,
    disableAria: name => `Отключить ${name}`,
    platformEnabled: name => `${name} включена`,
    platformDisabled: name => `${name} отключена`,
    restartToApply: 'Перезапустите шлюз для применения этого изменения.',
    setupSaved: name => `Настройка ${name} сохранена`,
    restartToReconnect: 'Перезапустите шлюз для переподключения с новыми учётными данными.',
    keyCleared: key => `${key} очищен`,
    setupUpdated: name => `Настройка ${name} обновлена.`,
    failedUpdate: name => `Не удалось обновить ${name}`,
    failedSave: name => `Не удалось сохранить ${name}`,
    failedClear: key => `Не удалось очистить ${key}`,
    fieldCopy: {},
    platformIntro: {}
  },

  profiles: {
    close: 'Закрыть профили',
    nameHint: 'Строчные буквы, цифры, дефисы и подчёркивания. Должно начинаться с буквы или цифры.',
    title: 'Профили',
    count: count => `${count} ${count === 1 ? 'профиль' : 'профилей'}`,
    loading: 'Загрузка профилей...',
    newProfile: 'Новый профиль',
    noProfiles: 'Профилей пока нет.',
    selectPrompt: 'Выберите профиль для просмотра.',
    refresh: 'Обновить профили',
    refreshing: 'Обновление профилей',
    default: 'по умолчанию',
    skills: count => `${count} ${count === 1 ? 'навык' : 'навыков'}`,
    env: 'env',
    defaultBadge: 'По умолчанию',
    rename: 'Переименовать',
    copySetup: 'Копировать настройку',
    copying: 'Копирование...',
    modelLabel: 'Модель',
    skillsLabel: 'Навыки',
    notSet: 'Не задано',
    soulDesc: 'Системный промпт и инструкции для личности, встроенные в этот профиль.',
    unsavedChanges: 'Несохранённые изменения',
    loadingSoul: 'Загрузка SOUL.md...',
    emptySoul: 'SOUL.md пуст — начните описывать личность...',
    saving: 'Сохранение...',
    saveSoul: 'Сохранить SOUL.md',
    deleteTitle: 'Удалить профиль?',
    deleteDescPrefix: 'Это удалит ',
    deleteDescMid: ' и удалит директорию ',
    deleteDescSuffix: '. Действие необратимо.',
    deleting: 'Удаление...',
    createDesc: 'Профили — независимые окружения Hermes: отдельная конфигурация, навыки и SOUL.md.',
    nameLabel: 'Имя',
    cloneFromDefault: 'Клонировать из профиля по умолчанию',
    cloneFromDefaultDesc: 'Скопировать конфигурацию, навыки и SOUL.md из профиля по умолчанию.',
    invalidName: hint => `Недопустимое имя. ${hint}`,
    nameRequired: 'Имя обязательно.',
    creating: 'Создание...',
    createAction: 'Создать профиль',
    renameTitle: 'Переименовать профиль',
    renameDescPrefix: 'Переименование обновляет директорию профиля и скрипты-обёртки в ',
    renameDescSuffix: '.',
    newNameLabel: 'Новое имя',
    renaming: 'Переименование...',
    created: 'Профиль создан',
    renamed: 'Профиль переименован',
    deleted: 'Профиль удалён',
    setupCopied: 'Команда настройки скопирована',
    soulSaved: 'SOUL.md сохранён',
    failedLoad: 'Не удалось загрузить профили',
    failedDelete: 'Не удалось удалить профиль',
    failedCopy: 'Не удалось скопировать команду настройки',
    failedLoadSoul: 'Не удалось загрузить SOUL.md',
    failedSaveSoul: 'Не удалось сохранить SOUL.md',
    failedCreate: 'Не удалось создать профиль',
    failedRename: 'Не удалось переименовать профиль'
  },

  cron: {
    close: 'Закрыть cron',
    search: 'Поиск cron-задач...',
    refresh: 'Обновить cron-задачи',
    refreshing: 'Обновление cron-задач',
    loading: 'Загрузка cron-задач...',
    states: {
      enabled: 'включена',
      scheduled: 'запланирована',
      running: 'выполняется',
      paused: 'на паузе',
      disabled: 'отключена',
      error: 'ошибка',
      completed: 'завершена'
    },
    deliveryLabels: {
      local: 'Этот десктоп',
      telegram: 'Telegram',
      discord: 'Discord',
      slack: 'Slack',
      email: 'Email'
    },
    scheduleLabels: {
      daily: 'Ежедневно',
      weekdays: 'По будням',
      weekly: 'Еженедельно',
      monthly: 'Ежемесячно',
      hourly: 'Ежечасно',
      'every-15-minutes': 'Каждые 15 минут',
      custom: 'Произвольное'
    },
    scheduleHints: {
      daily: 'Каждый день в 9:00',
      weekdays: 'С понедельника по пятницу в 9:00',
      weekly: 'Каждый понедельник в 9:00',
      monthly: 'Первое число каждого месяца в 9:00',
      hourly: 'В начале каждого часа',
      'every-15-minutes': 'Каждые 15 минут',
      custom: 'Cron-выражение или естественный язык'
    },
    days: {
      '0': 'Воскресенье',
      '1': 'Понедельник',
      '2': 'Вторник',
      '3': 'Среда',
      '4': 'Четверг',
      '5': 'Пятница',
      '6': 'Суббота',
      '7': 'Воскресенье'
    },
    dayFallback: value => `день ${value}`,
    everyDayAt: time => `Каждый день в ${time}`,
    weekdaysAt: time => `По будням в ${time}`,
    everyDayOfWeekAt: (day, time) => `Каждый ${day} в ${time}`,
    monthlyOnDayAt: (dayOfMonth, time) => `Ежемесячно ${dayOfMonth}-го в ${time}`,
    topOfHour: 'В начале каждого часа',
    everyHourAt: minute => `Каждый час в :${minute}`,
    active: (enabled, total) => `${enabled}/${total} активных`,
    newCron: 'Новая cron-задача',
    createFirst: 'Создать первую задачу',
    emptyDescNew:
      'Запланируйте запуск промпта по cron-выражению. Hermes будет выполнять его и отправлять результаты в указанное место.',
    emptyDescSearch: 'Попробуйте расширить запрос.',
    emptyTitleNew: 'Запланированных задач пока нет',
    emptyTitleSearch: 'Совпадений нет',
    last: 'Последний:',
    next: 'Следующий:',
    actionsFor: title => `Действия для ${title}`,
    actionsTitle: 'Действия cron-задачи',
    resume: 'Возобновить cron',
    pause: 'Поставить на паузу',
    resumeTitle: 'Возобновить',
    pauseTitle: 'Пауза',
    triggerNow: 'Запустить сейчас',
    edit: 'Редактировать cron',
    deleteTitle: 'Удалить cron-задачу?',
    deleteDescPrefix: 'Это удалит ',
    deleteDescSuffix: ' навсегда. Задача прекратит выполнение немедленно.',
    deleting: 'Удаление...',
    resumed: 'Cron возобновлён',
    paused: 'Cron поставлен на паузу',
    triggered: 'Cron запущен',
    deleted: 'Cron удалён',
    created: 'Cron создан',
    updated: 'Cron обновлён',
    failedLoad: 'Не удалось загрузить cron-задачи',
    failedUpdate: 'Не удалось обновить cron-задачу',
    failedTrigger: 'Не удалось запустить cron-задачу',
    failedDelete: 'Не удалось удалить cron-задачу',
    failedSave: 'Не удалось сохранить cron-задачу',
    editTitle: 'Редактировать cron-задачу',
    createTitle: 'Новая cron-задача',
    editDesc: 'Обновите расписание, промпт или место доставки. Изменения применятся при следующем запуске.',
    createDesc:
      'Запланируйте автоматический запуск промпта. Используйте cron-выражение или фразу типа «каждые 15 минут».',
    nameLabel: 'Имя',
    namePlaceholder: 'Утренняя сводка',
    promptLabel: 'Промпт',
    promptPlaceholder: 'Обобщи мои непрочитанные треды в Slack и отправь мне топ-5...',
    frequencyLabel: 'Частота',
    deliverLabel: 'Доставить в',
    customScheduleLabel: 'Произвольное расписание',
    customPlaceholder: '0 9 * * * или по будням в 9 утра',
    customHint: 'Cron-выражение или фразы типа «каждый час» или «по будням в 9 утра».',
    optional: 'Необязательно',
    promptScheduleRequired: 'Промпт и расписание обязательны.',
    saveChanges: 'Сохранить изменения',
    createAction: 'Создать cron'
  },

  artifacts: {
    search: 'Поиск артефактов...',
    refresh: 'Обновить артефакты',
    refreshing: 'Обновление артефактов',
    indexing: 'Индексация артефактов недавних сессий',
    tabAll: 'Все',
    tabImages: 'Изображения',
    tabFiles: 'Файлы',
    tabLinks: 'Ссылки',
    noArtifactsTitle: 'Артефакты не найдены',
    noArtifactsDesc: 'Созданные изображения и файлы появятся здесь по мере выполнения сессий.',
    failedLoad: 'Не удалось загрузить артефакты',
    openFailed: 'Ошибка открытия',
    itemsImage: 'изображений',
    itemsLink: 'ссылок',
    itemsFile: 'файлов',
    itemsGeneric: 'элементов',
    zero: '0',
    rangeOf: (start, end, total) => `${start}–${end} из ${total}`,
    goToPage: (itemLabel, page) => `Перейти к ${itemLabel}, страница ${page}`,
    colTitleLink: 'Название ссылки',
    colTitleFile: 'Имя',
    colTitleDefault: 'Название / имя',
    colLocationLink: 'URL',
    colLocationFile: 'Путь',
    colLocationDefault: 'Расположение',
    colSession: 'Сессия',
    kindImage: 'изображение',
    kindFile: 'файл',
    kindLink: 'ссылка',
    chat: 'Чат',
    copyUrl: 'Копировать URL',
    copyPath: 'Копировать путь'
  },

  sidebar: {
    nav: {
      'new-session': 'Новая сессия',
      skills: 'Навыки и инструменты',
      messaging: 'Мессенджеры',
      artifacts: 'Артефакты'
    },
    searchAria: 'Поиск сессий',
    searchPlaceholder: 'Поиск сессий…',
    clearSearch: 'Очистить поиск',
    noMatch: query => `Нет сессий, соответствующих «${query}».`,
    results: 'Результаты',
    pinned: 'Закреплённые',
    sessions: 'Сессии',
    groupAriaGrouped: 'Показать все сессии одним списком',
    groupAriaUngrouped: 'Сгруппировать сессии по рабочей области',
    groupTitleGrouped: 'Разгруппировать сессии',
    groupTitleUngrouped: 'Сгруппировать по рабочей области',
    allPinned: 'Все здесь закреплены. Открепите чат, чтобы он появился в недавних.',
    shiftClickHint: 'Shift+клик для закрепления · перетаскивание для изменения порядка',
    noWorkspace: 'Нет рабочей области',
    newSessionIn: label => `Новая сессия в ${label}`,
    reorderWorkspace: label => `Изменить порядок рабочей области ${label}`,
    showMoreIn: (count, label) => `Показать ещё ${count} в ${label}`,
    loading: 'Загрузка…',
    loadMore: 'Загрузить ещё',
    loadCount: step => `Загрузить ещё ${step}`,
    row: {
      pin: 'Закрепить',
      unpin: 'Открепить',
      copyId: 'Копировать ID',
      export: 'Экспорт',
      rename: 'Переименовать',
      archive: 'В архив',
      copyIdFailed: 'Не удалось скопировать ID сессии',
      actionsFor: title => `Действия для ${title}`,
      sessionActions: 'Действия сессии',
      sessionRunning: 'Сессия выполняется',
      needsInput: 'Требуется ваш ввод',
      waitingForAnswer: 'Ожидание вашего ответа',
      renamed: 'Переименовано',
      renameFailed: 'Ошибка переименования',
      renameTitle: 'Переименовать сессию',
      renameDesc: 'Дайте чату запоминающееся название. Оставьте пустым для очистки.',
      untitledPlaceholder: 'Сессия без названия',
      ageNow: 'сейчас',
      ageDay: 'д',
      ageHour: 'ч',
      ageMin: 'м'
    }
  },

  composer: {
    message: 'Сообщение',
    placeholderStarting: 'Запуск Hermes...',
    placeholderReconnecting: 'Переподключение к Hermes…',
    placeholderFollowUp: 'Отправить продолжение',
    newSessionPlaceholders: [
      'Что мы строим?',
      'Дайте Hermes задачу',
      'О чём вы думаете?',
      'Опишите, что нужно',
      'Что обсудим?',
      'Спросите что угодно',
      'Начните с цели'
    ],
    followUpPlaceholders: [
      'Отправить продолжение',
      'Добавить контекст',
      'Уточнить запрос',
      'Что дальше?',
      'Продолжаем',
      'Давайте дальше',
      'Скорректировать или продолжить'
    ],
    startVoice: 'Начать голосовой разговор',
    queueMessage: 'Поставить сообщение в очередь',
    steer: 'Направить текущий запуск (⌘⏎)',
    stop: 'Остановить',
    send: 'Отправить',
    speaking: 'Говорю',
    transcribing: 'Распознавание',
    thinking: 'Думаю',
    muted: 'Микрофон отключён',
    listening: 'Слушаю',
    muteMic: 'Отключить микрофон',
    unmuteMic: 'Включить микрофон',
    stopListening: 'Остановить запись и отправить',
    stopShort: 'Стоп',
    endConversation: 'Завершить голосовой разговор',
    endShort: 'Завершить',
    stopDictation: 'Остановить диктовку',
    transcribingDictation: 'Распознавание диктовки',
    voiceDictation: 'Голосовая диктовка',
    commonCommands: 'Основные команды',
    hotkeys: 'Горячие клавиши',
    helpFooter: 'открывает полную панель · Backspace закрывает',
    commandDescs: {
      '/help': 'полный список команд и горячих клавиш',
      '/clear': 'начать новую сессию',
      '/resume': 'продолжить предыдущую сессию',
      '/details': 'управление уровнем детализации',
      '/copy': 'скопировать выделение или последнее сообщение ассистента',
      '/quit': 'выйти из hermes'
    },
    hotkeyDescs: {
      '@': 'ссылки на файлы, папки, URL, git',
      '/': 'палитра слеш-команд',
      '?': 'эта быстрая справка (удалите для закрытия)',
      Enter: 'отправить · Shift+Enter для перевода строки',
      'Cmd/Ctrl+K': 'отправить следующее сообщение из очереди',
      'Cmd/Ctrl+L': 'перерисовать',
      Esc: 'закрыть всплывающее окно · отменить запуск',
      '↑ / ↓': 'переключение в окне / история'
    },
    attachUrlTitle: 'Прикрепить URL',
    attachUrlDesc: 'Hermes загрузит страницу и включит её как контекст для этого хода.',
    urlPlaceholder: 'https://example.com/post',
    urlHintPre: 'Укажите полный URL, например ',
    attach: 'Прикрепить',
    queued: count => `${count} в очереди`,
    attachmentOnly: 'Ход только с вложением',
    emptyTurn: 'Пустой ход',
    attachments: count => `${count} ${count === 1 ? 'вложение' : 'вложений'}`,
    editingInComposer: 'Редактирование в поле ввода',
    editQueued: 'Редактирование очередного хода',
    sendQueuedNext: 'Отправить очередь следующим',
    sendQueuedNow: 'Отправить очередь сейчас',
    deleteQueued: 'Удалить очередь',
    previewUnavailable: 'Предпросмотр недоступен',
    previewLabel: label => `Предпросмотр ${label}`,
    couldNotPreview: label => `Не удалось показать предпросмотр ${label}`,
    removeAttachment: label => `Удалить ${label}`,
    dictating: 'Диктовка',
    preparingAudio: 'Подготовка аудио',
    speakingResponse: 'Озвучиваю ответ',
    readingAloud: 'Читаю вслух',
    themeSuggestions: 'Предложения тем десктопа',
    noMatchingThemes: 'Подходящих тем нет.',
    themeTryPre: 'Попробуйте ',
    themeTryPost: '.',
    attachLabel: 'Прикрепить',
    files: 'Файлы…',
    folder: 'Папка…',
    images: 'Изображения…',
    pasteImage: 'Вставить изображение',
    url: 'URL…',
    promptSnippets: 'Фрагменты промпта…',
    tipPre: 'Подсказка: введите ',
    tipPost: ' для вставки файлов.',
    snippetsTitle: 'Фрагменты промпта',
    snippetsDesc: 'Выберите готовый промпт для вставки в поле ввода.',
    snippets: {
      codeReview: {
        label: 'Обзор кода',
        description: 'Проверить текущее изменение на регрессии, потерянные граничные случаи и отсутствующие тесты.',
        text: 'Пожалуйста, проверьте этот код на ошибки, регрессии и отсутствующие тесты.'
      },
      implementationPlan: {
        label: 'План реализации',
        description: 'Наметить подход перед изменением кода, чтобы дифф оставался фокусированным.',
        text: 'Пожалуйста, составьте краткий план реализации перед изменением кода.'
      },
      explainThis: {
        label: 'Объяснить код',
        description: 'Разобрать, как работает выбранный код, и указать на ключевые файлы.',
        text: 'Пожалуйста, объясните, как это работает, и укажите ключевые файлы.'
      }
    }
  },

  sessionsPage: {
    archivedSessions: 'Архивные сессии',
    archivedSessionsDesc: 'Архивные чаты скрыты из боковой панели, но сохраняют все сообщения. Ctrl/⌘+клик по чату в боковой панели для архивации.',
    nothingArchived: 'Нет архивных чатов',
    archiveHint: 'Архивируйте чат, чтобы скрыть его здесь.',
    defaultProjectDir: 'Директория проекта по умолчанию',
    defaultProjectDirDesc: 'Новые сессии начинаются в этой папке, если не выбрана другая. Оставьте пустым для использования домашней директории.',
    notSet: 'Не задано',
    choose: 'Выбрать',
    change: 'Изменить',
    clear: 'Очистить',
    unarchive: 'Разархивировать',
    messages: (count: number) => `${count} ${count === 1 ? 'сообщение' : count < 5 ? 'сообщения' : 'сообщений'}`,
    confirmDeleteTitle: 'Удалить безвозвратно?',
    confirmDeleteMessage: (title: string) => `Безвозвратно удалить "${title}"? Это действие необратимо.`,
    restored: 'Восстановлено',
    unarchiveFailed: 'Не удалось разархивировать',
    deleteFailed: 'Не удалось удалить',
    loadFailed: 'Не удалось загрузить архивные сессии',
    dirUpdated: 'Директория проекта по умолчанию обновлена',
    dirUpdateFailed: 'Не удалось обновить директорию по умолчанию',
    dirCleared: 'Директория по умолчанию очищена',
    dirClearFailed: 'Не удалось очистить директорию по умолчанию'
  },

  mcpPage: {
    newServer: 'Новый сервер',
    editServer: 'Редактировать сервер',
    reloadMcp: 'Перезагрузить MCP',
    reloading: 'Перезагрузка...',
    noServers: 'Нет MCP-серверов',
    noServersDesc: 'Добавьте stdio или HTTP-сервер для доступа к MCP-инструментам.',
    name: 'Имя',
    serverJson: 'JSON сервера',
    saveServer: 'Сохранить сервер',
    saving: 'Сохранение...',
    remove: 'Удалить',
    disabled: 'отключён',
    nameRequired: 'Требуется имя',
    nameRequiredDesc: 'Укажите ключ конфигурации для этого MCP-сервера.',
    invalidJson: 'Некорректный JSON MCP',
    serverSaved: 'MCP-сервер сохранён',
    serverSavedDesc: (name: string) => `${name} применится после перезагрузки MCP.`,
    saveFailed: 'Не удалось сохранить',
    removeFailed: 'Не удалось удалить',
    gatewayUnavailable: 'Шлюз недоступен',
    gatewayUnavailableDesc: 'Переподключите шлюз перед перезагрузкой MCP.',
    toolsReloaded: 'MCP-инструменты перезагружены',
    toolsReloadedDesc: 'Новые схемы инструментов применятся к новым ходам.',
    reloadFailed: 'Не удалось перезагрузить MCP',
    loadFailed: 'Не удалось загрузить конфигурацию MCP'
  },

  gatewayPage: {
    gatewayConnection: 'Подключение к шлюзу',
    gatewayConnectionDesc: 'Hermes Desktop запускает собственный локальный шлюз по умолчанию. Используйте удалённый шлюз, когда хотите, чтобы приложение управляло уже запущенным бэкендом Hermes на другой машине или за прокси. Выберите профиль ниже для настройки удалённого хоста.',
    appliesTo: 'Применяется к',
    defaultConnection: 'Соединение по умолчанию для профилей без собственных настроек.',
    profileConnection: (scope: string) => `Соединение используется только когда "${scope}" — активный профиль. Установите «Локальный» для наследования настроек по умолчанию.`,
    envOverride: 'переменные окружения',
    envOverrideWarning: 'Переменные окружения управляют этой сессией десктопа.',
    unset: 'Убрать',
    and: 'и',
    useSavedSetting: 'для использования сохранённой настройки ниже.',
    localGateway: 'Локальный шлюз',
    localGatewayDesc: 'Запустить приватный бэкенд Hermes на localhost. Это настройка по умолчанию, работает офлайн.',
    remoteGateway: 'Удалённый шлюз',
    remoteGatewayDesc: 'Подключить этот десктоп к удалённому бэкенду Hermes. Облачные шлюзы используют OAuth или логин/пароль; собственные — могут использовать токен сессии.',
    remoteUrl: 'Удалённый URL',
    remoteUrlDesc: 'Базовый URL удалённого дашборда. Поддерживаются префиксы путей, например /hermes.',
    remoteUrlPlaceholder: 'https://gateway.example.com/hermes',
    authentication: 'Аутентификация',
    sessionToken: 'Токен сессии',
    sessionTokenDesc: 'Токен сессии дашборда для REST и WebSocket. Оставьте пустым для сохранения текущего токена.',
    tokenPlaceholder: 'Вставьте токен сессии',
    existingToken: (preview: string) => `Текущий токен: ${preview}`,
    pasteToken: 'Вставьте токен сессии',
    diagnostics: 'Диагностика',
    diagnosticsDesc: 'Открыть desktop.log в файловом менеджере — полезно при проблемах с запуском шлюза.',
    openLogs: 'Открыть журналы',
    testRemote: 'Тест соединения',
    saveForNextRestart: 'Сохранить для следующего перезапуска',
    saveAndReconnect: 'Сохранить и переподключиться',
    checkingAuth: 'Проверка способа аутентификации шлюза...',
    couldNotReach: 'Не удалось подключиться к шлюзу. Проверьте URL — способ аутентификации появится после ответа.',
    signedIn: 'Вход выполнен',
    signOut: 'Выйти',
    signIn: 'Войти',
    signInWith: (provider: string) => `Войти через ${provider}`,
    passwordAuthSignedIn: 'Этот шлюз использует логин и пароль. Вы вошли; сессия обновляется автоматически.',
    oauthAuthSignedIn: 'Этот шлюз использует OAuth. Вы вошли; сессия обновляется автоматически.',
    passwordAuthSignIn: 'Этот шлюз использует логин и пароль. Войдите для авторизации этого приложения.',
    oauthAuthSignIn: (provider: string) => `Этот шлюз использует OAuth. Войдите через ${provider} для авторизации этого приложения.`,
    envOverrideActive: 'Переменные окружения управляют этой сессией десктопа.',
    settingsUnavailable: 'Настройки шлюза недоступны',
    settingsUnavailableDesc: 'IPC-мост десктопа не предоставляет настройки шлюза.'
  }
}
